version: '3.9'
services:
  web:
    image: 'nginx:mainline-alpine'
    container_name: uts-quiz-web
    hostname: uts-quiz-web
    volumes:
      - './public:/app/public:ro'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    working_dir: /app
    ports:
      - 8000:80

  php:
    image: 'php:fpm'
    container_name: uts-quiz-php
    hostname: uts-quiz-php
    volumes:
      - '.:/app'
    working_dir: /app