<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200114065503 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE city (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, country_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL)');
        $this->addSql('CREATE INDEX IDX_2D5B0234F92F3E70 ON city (country_id)');
        $this->addSql('CREATE TABLE country (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL)');
        $this->addSql('CREATE TABLE currency (id VARCHAR(3) NOT NULL, rate DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE hotel (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, city_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL)');
        $this->addSql('CREATE INDEX IDX_3535ED98BAC62AF ON hotel (city_id)');
        $this->addSql('CREATE TABLE meal (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL)');
        $this->addSql('CREATE TABLE search_request (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, city_id INTEGER NOT NULL, check_in DATE NOT NULL, check_out DATE NOT NULL)');
        $this->addSql('CREATE INDEX IDX_B64660058BAC62AF ON search_request (city_id)');
        $this->addSql('CREATE TABLE search_result (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, request_id INTEGER NOT NULL, hotel_id INTEGER NOT NULL, meal_id INTEGER DEFAULT NULL, room_name VARCHAR(255) NOT NULL, compare_price INTEGER NOT NULL, price_amount NUMERIC(2, 8) NOT NULL, price_currency VARCHAR(3) NOT NULL)');
        $this->addSql('CREATE INDEX IDX_CA88AE0C427EB8A5 ON search_result (request_id)');
        $this->addSql('CREATE INDEX IDX_CA88AE0C3243BB18 ON search_result (hotel_id)');
        $this->addSql('CREATE INDEX IDX_CA88AE0C639666D6 ON search_result (meal_id)');
        $this->addSql('CREATE INDEX search_result_compare ON search_result (compare_price)');
        $this->addSql('CREATE TABLE special_offer (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, country_id INTEGER NOT NULL, city_id INTEGER DEFAULT NULL, hotel_id INTEGER DEFAULT NULL, description VARCHAR(255) NOT NULL, discount_type VARCHAR(1) NOT NULL, discount_value INTEGER NOT NULL)');
        $this->addSql('CREATE INDEX IDX_85E8297FF92F3E70 ON special_offer (country_id)');
        $this->addSql('CREATE INDEX IDX_85E8297F8BAC62AF ON special_offer (city_id)');
        $this->addSql('CREATE INDEX IDX_85E8297F3243BB18 ON special_offer (hotel_id)');

        $this->addSql("INSERT INTO country (name) VALUES ('Великобритания')");
        $this->addSql("INSERT INTO country (name) VALUES ('Россия')");
        $this->addSql("INSERT INTO city (name, country_id) VALUES ('Лондон', 1)");
        $this->addSql("INSERT INTO city (name, country_id) VALUES ('Москва', 2)");
        $this->addSql("INSERT INTO city (name, country_id) VALUES ('Санкт-Петербург', 2)");
        $this->addSql("INSERT INTO  currency (id, rate) VALUES ('EUR',89.33)");
        $this->addSql("INSERT INTO  currency (id, rate) VALUES ('RUB',1)");
        $this->addSql("INSERT INTO  currency (id, rate) VALUES ('USD',73.72)");
        $this->addSql("INSERT INTO meal (id, name) VALUES (23, 'Завтрак для двоих')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (2, 'Завтрак')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (10, 'Полный пансион')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (61, 'Английский завтрак')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (26, 'Завтрак буфет')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (18, 'Континентальный завтрак')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (4, 'Завтрак + обед')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (6, 'Без питания')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (3, 'Завтрак + ужин')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (119, 'Завтрак для одного')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (117, 'Континентальный завтрак для двоих')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (120, 'Полный завтрак')");
        $this->addSql("INSERT INTO meal (id, name) VALUES (121, 'Бесплатный завтрак')");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (6, 'Отель Россия', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (7, 'Отель Рэдиссон Ройал, Санкт-Петербург', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (9, 'Отель Парк Инн Пулковская', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (14, 'Петро Палас Отель', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (19, 'Арт-отель Карелия (бывш.Бизнес-отель Карелия)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (25, 'Гранд Отель Эмеральд', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26, 'Отель Достоевский', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39, 'Radisson Collection Hotel Moscow (бывш. Рэдиссон Роял Москва / Украина)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (41, 'Свиссотель Красные Холмы', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (45, 'Савой Отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (46, 'Азимут Отель Олимпик Москва', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (47, 'Рэдиссон Славянская Отель и Бизнес Центр', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (48, 'Новотель Москва Центр', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (52, 'Бизнес-отель Россо Рива (бывш.Катерина Сити)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (53, 'Холидей Инн Москва Селигерская (Holiday Inn Moscow Seligerskaya)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (58, 'Отель Космос', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11475, 'Wedgewood', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11476, 'Mercure London Bloomsbury', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11477, 'Washington Mayfair Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11491, 'Amba Hotel Grosvenor', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11493, 'Thistle Piccadilly (ex. Every Hotel Piccadilly)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11494, 'Amba Hotel Marble Arch (ex. Thistle Marble Arch)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11495, 'Lancaster Gate Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11498, 'Thistle Kensington Gardens', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11500, 'Thistle Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11502, 'Thistle City Barbican, Shoreditch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11503, 'Amba Hotel Charing Cross', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11504, 'Thistle Bloomsbury Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11505, 'Thistle Holborn, The Kingsley', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11517, 'St Giles London - A St Giles Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11518, 'Treehouse Hotel London (ex.Saint Georges Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11521, 'Somerset Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11522, 'Sofitel London St James', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11525, 'Holmes Hotel London (ex.Park Plaza Sherlock Holmes London)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11535, 'Shakespeare Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11538, 'Park Grand London Kensington (ex. Best Western Premier)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11541, 'Seymour Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11543, 'The Savoy', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11549, 'Kimpton Fitzroy LondonH (ex.The Principal London/Russel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11550, 'The Rubens At The Palace', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11555, 'Royal Lancaster London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11560, 'ROYAL EAGLE', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11564, 'Rose Park Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11565, 'Park Plaza Riverbank London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11567, 'The Ritz London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11569, 'Rosewood London (ex.Chancery Court)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11577, 'Doubletree By Hilton London - Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11578, 'Holiday Inn London West (ex. Ramada Encore London)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11588, 'Quality Hotel Hampstead', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11589, 'Mercure London Paddington Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11609, 'Novotel London Waterloo', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11610, 'Novotel London Tower Bridge', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11613, 'Novotel London Bridge Hotel (ex.Novotel London City South)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11614, 'Novotel London Greenwich', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11616, 'Pullman London St Pancras', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11617, 'Norfolk Towers Paddington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11623, 'Nayland Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11625, 'Myhotel Bloomsbury', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11626, 'Mowbray Court Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11631, 'Mitre House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11634, 'Millennium Hotel London Knightsbridge', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11636, 'Millennium Gloucester Hotel London Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11638, 'The Bailey’s Hotel London (ex. Millennium Bailey’s Hotel London Kensington)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11640, 'The Milestone Hotel & Residences', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11641, 'COMO Metropolitan London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11649, 'The Mandeville Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11650, 'Mandarin Oriental Hyde Park, London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11656, 'London House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11657, 'London Elizabeth Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11661, 'Leonard', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11663, 'LEIGHAM COURT', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11673, 'K+k Hotel George', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11675, 'KINGS', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11686, 'K West Hotel & Spa', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11688, 'The Kensington Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11689, 'Doubletree by Hilton Angel Kings Cross (ex. DoubleTree by Hilton Hotel London - Islington)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11690, 'DoubleTree by Hilton Hotel London - Chelsea', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11692, 'The Marylebone Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11697, 'InterContinental London Park Lane', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11702, 'Ibis London Earls Court', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11703, 'ibis London City - Shoreditch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11709, 'Hyatt Regency London - The Churchill', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11717, 'Holiday Inn London - Regents Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11721, 'Crowne Plaza London - Kings Cross (ex. Holiday Inn London - Kings Cross Bloomsbury)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11722, 'Holiday Inn London - Kensington Forum', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11724, 'Crowne Plaza London Ealing', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11728, 'Holiday Inn London - Bloomsbury', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11739, 'Hilton London Olympia', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11740, 'Hilton London Metropole', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11742, 'Hilton London Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11744, 'Hilton London Angel Islington (ex. Hilton London Islington)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11745, 'Hilton London Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11749, 'Hilton London Euston', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11751, 'DoubleTree by Hilton London - Docklands Riverside (ex. Hilton London Docklands Riverside)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11756, 'Hanover Hotel Victoria London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11761, 'GUILFORD', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11784, 'The Exhibitionist Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11796, 'Holiday Inn Express Chingford North Circular', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11797, 'Holiday Inn Express London City', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11798, 'Holiday Inn Express London Hammersmith', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11800, 'Holiday Inn Express London-Royal Docks, Docklands', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11805, 'Exhibition Court Hotel 4', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11814, 'OYO Elysee Hotel (ex. Elysee Hotel Hyde Park)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11816, 'The Dorchester - Dorchester Collection', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11820, 'Dolphin Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11822, 'Ramada London North M1', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11825, 'Danubius Hotel Regents Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11828, 'Hard Rock Hotel London (ex. Cumberland)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11829, 'Crowne Plaza London - The City', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11830, 'Crowne Plaza London - Docklands', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11831, 'St. James Court, A Taj Hotel, London (ex. Crowne Plaza St. James)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11835, 'Courthouse Hotel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11846, 'The Connaught', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11854, 'The Premier Notting Hill', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11856, 'Claridges', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11859, 'Doubletree By Hilton London - Westminster (ex. City Inn Westminster)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11860, 'Citadines Holborn-Covent Garden London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11862, 'Citadines Barbican London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11868, 'The Cavendish London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11873, 'The Capital', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11874, 'Caesar Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11877, 'Byron', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11882, 'Britannia International Hotel Canary Wharf', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11889, 'Blakemore Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11891, 'BEVERLEY CITY', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11892, 'Best Western Swiss Cottage Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11894, 'Park Grand Paddington Court London (ex. Best Western Shaftesbury Paddington Court)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11899, 'The Berkeley', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11903, 'The Bentley London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11908, 'Bayswater Inn', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11915, 'Astor Court Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11917, 'APOLLO', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11918, 'Apex City of London Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11924, 'Alexandra Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11925, 'ADMIRAL', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11929, 'Taj 51 Buckingham Gate Suites and Residences', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (11931, '196 Bishopsgate', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (24566, 'Домодедово Аэротель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (24772, 'Holiday Inn London - Kensington High St. (ex. Kensington Close Hotel And Spa)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (24819, 'Queens Park Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (25525, 'Отель Парк Инн Прибалтийская', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26049, 'Cromwell International Hotel London (ex.Cromwell Crown)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26056, 'Generator Hostel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26058, 'The Gresham Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26059, 'Henley House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26068, 'Radisson Blu Edwardian, Berkshire', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26070, 'Radisson Blu Edwardian Grafton Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26071, 'Radisson Blu Edwardian Kenilworth', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26072, 'Radisson Blu Edwardian Bloomsbury Street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26073, 'Radisson Blu Edwardian Vanderbilt Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26181, 'Americana Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26287, 'Волга Апарт-Отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26346, 'The Royal Horseguards', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26358, 'DoubleTree by Hilton Hotel London ExCel (ex. Ramada Hotel & Suites London Docklands)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26390, 'NH London Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26395, 'Clayton Hotel Chiswick (ex. Chiswick Moran Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26423, 'Кемпински Отель Мойка 22', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26441, 'Золотое кольцо', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26443, 'The Hoxton, Shoreditch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26461, 'The Goring', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26462, 'Бутик-отель Автор (ранее Голден Гарден)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26463, 'Чехофф Отель Москва Кьюрио Коллекшен Хилтон', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (26669, 'The Nadler Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (27844, 'Hilton London Canary Wharf', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (28338, 'Rushmore Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (28770, 'Euston Square Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (28904, 'Roseate House London (ex.The Royal Park)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (28998, 'Холидей Инн Москва Сокольники (Holiday Inn Moscow Sokolniki)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (29015, 'Милан отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (29467, 'TROY', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (29729, 'Mayflower Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (29845, 'AQUARIUS', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (29920, 'New Linden', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (30063, 'Millennium & Copthorne Hotels at Chelsea Football Club', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (30068, 'The Cranley Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (30205, 'OLIVER PLAZA', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (30306, 'Du Vin Wimbledon Cannizaro House hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (30403, 'Петро Спорт Отель', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (30541, 'Holiday Inn Express London - Stratford', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (30616, 'Comfort Inn Edgware Road', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (31515, 'Бородино Бизнес-Отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (31573, 'Flemings Mayfair', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (31592, 'Park Plaza Victoria London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (31595, 'Mercure London Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (31596, 'Radisson Blu Edwardian Hampshire Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (32401, 'Doubletree By Hilton London - West End (ex. Park Inn Russell)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (32824, 'Fraser Suites Queens Gate, London (ex. Fraser Place)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (33026, 'Park Plaza County Hall London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (33313, 'Будапешт гостиница', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (33454, 'Петр 1', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (33455, 'Мамаизон спа отель Покровка', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (33510, 'Ramada London Finchley (ex. Comfort Finchley)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (33961, 'Best Western Mornington Hotel London Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34208, 'Sanctum Soho Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34590, 'Eurotraveller Hotel- Express (ex.Elephant & Castle)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34848, 'Ashburn Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34852, 'Mama Shelter London (ex.The RE London Shoreditch)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34853, 'EDWARD', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34857, 'Hyde Park Executive Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34858, 'King Solomon Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34860, 'The Chelsea Harbour Hotel (ex. Wyndham Grand Chelsea Harbour)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34864, 'Chilworth London Paddington (ex. Shaftesbury Premier London Paddington)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34865, 'The Piccadilly London West End', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34872, 'Prince William', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34895, 'Амбассадор отель', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (34984, 'Citadines South Kensington London (ex.Citadines Prestige South Kensington)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (35155, 'Соло Сокос Палас Бридж отель', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (35173, 'Отель Ибис Санкт-Петербург Центр', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (35180, 'Измайлово Бета', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (35181, 'Измайлово Гамма', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (35421, 'Ориджинал Сокос Отель Олимпия Гарден', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (35423, 'Соло Сокос Васильевский отель', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (35549, 'Hyde Park Suites (ex. London Apartment)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (35555, 'Viking Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38208, 'Аэростар отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38209, 'Азимут Отель Санкт-Петербург', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38212, 'Бельмонд Гранд Отель Европа', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38304, '41', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38309, 'Britannia Hampstead', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38311, 'Comfort Inn Victoria', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38343, 'Ashley London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38347, 'Chelsea Cloisters', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38351, 'Days Inn Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38364, 'The Royale Chulan Hyde Park Hotel (ex. So Hyde Park)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38390, 'So Sienna', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38743, 'Rocco Forte Browns Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38746, 'Copthorne Tara Hotel London Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38748, 'Holiday Inn Express London - Limehouse', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38749, 'Holiday Inn Express London Southwark', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38751, 'Hilton London Paddington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38755, 'The Bloomsbury Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (38809, 'The May Fair, A Radisson Collection Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39297, 'NEW DAWN', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39779, 'Отель на Казачьем (б. Алроса на Казачьем)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39781, 'Измайлово Альфа', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39783, 'Арбат', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39787, 'Измайлово Вега', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39789, 'Даниловская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39795, 'Амбассадори (ранее Кебур Палас)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39798, 'Краун Плаза Москва Центр Международной Торговли (Crowne Plaza Hotel  Moscow World Trade Centre)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39801, 'Отель Митино', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39802, 'Отель Парк Тауэр (бывший Молодежный)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39807, 'Охотник', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39808, 'Парк Инн Саду', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39809, 'Отель Пекин', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39812, 'Президент-Отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39813, 'Протон Бизнес Отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39815, 'Гостиница Салют', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39818, 'Славянка', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39821, 'Гостиница Сретенская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39825, 'Хилтон Москва Ленинградская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39826, 'Аструс- Центральный Дом Туриста', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39832, 'Отель Алиот', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39863, 'Октябрьская', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39873, 'Росси Бутик Отель', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (39887, 'Талион Империал Отель', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (40188, 'Конгресс-Парк Волынское', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (40189, 'РСВО (бывш. Мирит)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (40191, 'Мини-отель Лось', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (40203, 'Холидей Инн Московские Ворота (Holiday Inn Moskovskye Vorota)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (43570, 'Best Western The Boltons Hotel London Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (43659, 'COLLIERS', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (43690, 'Malmaison London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (43707, 'Oxford Hotel Earls Court', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (43711, 'Mercure London Hyde Park (ex.Quality Crown Hyde Park)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (43720, 'St. James Hotel and Club Mayfair', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (43841, 'Grand Plaza Serviced Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (43922, 'Novotel London Paddington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (43929, 'Shaftesbury Hyde Park International', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (44241, 'Гостиница Академическая', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (44243, 'Гостиница Металлург', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (48430, 'Холидей Инн Таганский (Holiday Inn Tagansky)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (48859, 'Мармара', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (49414, 'Doubletree by Hilton London Marble Arch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (50120, 'Bermondsey Square', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (50122, 'Phoenix Hotel (ex. Best Western)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (51603, 'The Montcalm London Marble Arch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (52388, 'Apex London Wall Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (52392, 'Hotel Indigo London - Paddington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (52393, 'Linden House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (54066, 'Отель Орбита', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (54067, 'Отель Парк Крестовский', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (54072, 'Отель Ибис Москва Павелецкая', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (54525, 'Comfort Inn St. Pancras Kings Cross', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (54526, 'Crescent Hyde Park London (ex. Paddington Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (55863, 'М-Отель', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (55864, 'Отель Рэдиссон Соня', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (56984, 'London Guards Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (57659, 'Ten Manchester Street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (57665, 'Crowne Plaza London Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (57670, 'Radisson Blu Edwardian, Sussex', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (57673, 'Radisson Edwardian New Providence Wharf', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (57687, 'The Beaufort Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (60036, 'Park Plaza Westminster Bridge London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (63517, 'The Rembrandt Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (65090, 'Гостиница Бега', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (65488, 'Crowne Plaza Третьяковская (ранее Аквамарин)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (70732, 'H10 London Waterloo', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (70744, 'Park Grand London Lancaster Gate (ex. Hyde Park Premier London Paddington)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (70750, 'Park Grand London Paddington Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (70751, 'Pestana Chelsea Bridge Hotel & Spa', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (70875, 'Grand Royale London Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (74070, 'Юность', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (77371, 'Парк Инн Невский', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (83670, 'Сан Флауэр Парк Отель (бывш. Катерина Парк)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (83999, 'Азимут Отель Смоленская Москва (ранее Белград)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87274, 'Airways Hotel Victoria, London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87278, 'Best Western Chiswick Palace & Suites', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87284, 'Columbia', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87351, 'Ibis London Stratford', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87362, 'Lord Jim hotel London Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87366, 'Marlin Apartments Empire Square', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87415, 'The Chesterfield Mayfair', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87417, 'The Cleveland', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87422, 'The Egerton House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87443, 'The Montague on the Gardens', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (87455, 'Trebovir London (ex. Grand Hotel London)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88475, 'Гостиница Москомспорта', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88479, 'Гостиница Университетская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88486, 'Новотель Санкт-Петербург Центр', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88489, 'Отель Санкт-Петербург', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88928, 'Wellington Hotel by Blue Orchid (ex. Grange Wellington Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88931, 'The Lancaster', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88933, 'Strathmore Hotel (ex.Grange Strathmore)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88934, 'Grange Portland Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88935, 'Grange White Hall Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88936, 'Grange The Buckingham', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88937, 'Grange Clarendon Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88939, 'The Beauchamp Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88941, 'Leonardo Royal Hotel London City (ex. Grange City Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88942, 'Leonardo Royal Hotel London St Paul’s (ex. Grange St Pauls)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88943, 'Fitzrovia Hotel (ex. Grange Fitzrovia)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88944, 'Langham Court (ex.Grange Langham Court)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (88945, 'Rochester Hotel by Blue Orchid (ex.Grange Rochester Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (89079, 'St Joseph Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (89110, 'Лотте Отель Москва', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (89201, 'Best Western Seraphine Kensington Olympia', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (89204, '100 Queens Gate Hotel London, Curio Collection by Hilton (ex. Doubletree by Hilton London - Kensington / Regency Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (89270, 'Wimbledon', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (89366, 'Four Seasons Hotel London at Park Lane', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (89485, 'Москоу Холидэй Отель(ex. Кассадо Плаза)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90968, 'Normandie', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90972, 'Central Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90973, 'Charlies', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90975, 'Dover Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90983, 'Hostel 639- HSD', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90984, 'Hyde Park Court', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90987, 'Plaza Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90989, 'Saint Simeon - HSD', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90992, 'Stauton', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90994, 'Tudor Inn Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90995, 'Ventures Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (90997, 'Boston Court Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (91231, 'Ravna Gora', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (91404, 'СК Роял Отель Москва', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (91487, 'Гостиница Таврическая', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (91494, 'Апарт-отель «Кронверк»', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (91600, 'DoubleTree by Hilton Hotel London - Tower of London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (91667, 'ibis Styles London Southwark - near Borough Market Hotel (ex.Ibis Styles London Southwark Rose Hotel) 3*', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (92697, 'SO Sofitel St.Petersburg (ранее Отель W Cанкт-Петербург)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (92734, 'Краун Плаза Лиговский (Crowne Plaza St. Petersburg - Ligovsky)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (96043, 'The Lodge Hotel - Putney', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (96046, 'Corinthia Hotel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (96074, 'London Waterloo Hostel (ex. London Eye Hostel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (96107, 'Smart Hyde Park Inn Hostel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (110325, 'Краун Плаза Санкт-Петербург Аэропорт (Crowne Plaza St. Petersburg Airport)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (110334, 'Интерконтиненталь Москва Тверская (InterContinental Moscow Tverskaya)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (110340, 'Отель Рэдиссон Блу Белорусская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (110343, 'Стейбридж Сьютс (Staybridge Suites)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (113406, 'Введенский', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (114003, 'Бест Вестерн Плюс Центр Отель (быв. Октябрьская корп. Лиговский)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (114190, 'Гостиница Лефортово', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (114202, 'Гостиница Сокол', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (114554, 'Багратион отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (119014, 'Лефортовский Мост', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (119016, 'Отель МосУз Центр', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (119034, 'Домина Санкт-Петербург', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (119036, 'Отель Парк Львиный Мостик (ранее Отель История на Канале Грибоедова)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (119374, 'Indigo London Tower Hill', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (119376, 'Conrad London St. James', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (121374, 'Holiday Inn Express London - Park Royal', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (122272, 'Thistle Trafalgar Square (ex.Royal Trafalgar by Thistle)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (125170, 'Отель Меркюр Арбат Москва', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (127132, 'Comfort Inn Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (127161, 'Maranton House Hotel Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (127162, 'Marble Arch Inn Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (127167, 'Opulence Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (127181, 'Sheriff Hotel (ex. Sheriff Inn)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (127187, 'Point A Hotel London Kings Cross (ex. Tune Hotel King Cross)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (127188, 'Point A London Liverpool Street (ex. Tune Hotel Liverpool Street)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (127809, 'Apex Temple Court Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (128075, 'Holiday Inn London - Whitechapel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (131622, 'Азимут Москва  Тульская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (132593, 'Holiday Inn London - Stratford City', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (133236, 'Best Western Plus Seraphine Hammersmith Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (133333, 'The Wesley London Euston', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (133352, 'The Ampersand', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (133619, 'Bulgari Hotel, London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (139436, 'Chiswick Rooms', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (140234, 'The Prince Akatoki London (ex. The Arch London)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (140798, 'Hotel Indigo London - Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (140806, 'ME London by Melia', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (140810, 'DoubleTree by Hilton London - Greenwich (ex. Mercure London Greenwich)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (140811, 'Novotel London Blackfriars', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (140818, 'Staybridge Suites London- Stratford', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (140827, 'The Marble Arch by Montcalm London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (143331, 'Point A Hotel London Paddington (ex. Tune Hotel Paddington)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (143333, 'Park International Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (143724, 'DoubleTree by Hilton London Victoria (ex. Hesperia London Victoria)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (148481, 'Ibis London Blackfriars', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (154367, 'Hotel Cafe Royal', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (163506, 'The Colonnade', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167526, 'Best Western London Highbury', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167554, 'Leonardo Royal Hotel London Tower Bridge (ex. Grange Tower Bridge Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167559, 'Hyde Park Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167573, 'Paddington Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167574, 'Paddington Court Rooms', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167575, 'Palace Court', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167592, 'So Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167594, 'Staycity Aparthotels London Heathrow', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167595, 'Studios2let', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167599, 'Mornington Hotel London Victor (ex.The Caswell)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167600, 'Comfotel Grn', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167601, 'Grantly Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167603, 'The Montcalm at the Brewery London City', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (167614, 'The W14 Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (168947, 'Индиго Санкт-Петербург - Чайковского', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (169262, 'Инсайд Бизнес Румянцево', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (171537, 'Hyde Park Boutique Hotel (ex. Holiday House)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (176152, 'Classic', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (176172, 'Radisson Blu Edwardian Mercer Street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (184468, 'The Westbridge Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (184469, 'Newham Hotel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (194084, 'Native Hyde Park (ex. Go Native Hyde Park)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196412, '27 Paddington Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196427, 'Amsterdam Hotel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196437, 'OYO Anchor Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196471, 'Bakers Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196477, 'Barry House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196527, 'Blandford Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196535, 'The Brompton Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196555, 'Cheval Phoenix House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196560, 'Church Street Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196563, 'citizenM London Bankside', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196582, 'Club Quarters Lincolns Inn Fields', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196583, 'Club Quarters St. Pauls', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196584, 'Club Quarters Hotel, Gracechurch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196585, 'Club Quarters Hotel, Trafalgar Square', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196608, 'Comfotel Blue', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196669, 'Elmwood Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196676, 'Canary Riverside Plaza (ex. Four Seasons London at Canary Wharf)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196971, 'ibis London Docklands Canary Wharf', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196974, 'ibis London Greenwich', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196975, 'ibis London Shepherds Bush - Hammersmith Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196981, 'Jubilee Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196984, 'Kensington Court Hotel Notting Hill', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196985, 'Kings Boutique Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196986, 'Kings Cross Inn Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196990, 'La Gaffe', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196992, 'Lancaster Court Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (196993, 'Leigh House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197003, 'Doubletree By Hilton London - Ealing Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197060, 'Melita House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197065, 'Mercure London Bridge Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197094, 'New England Hotel (ex.OYO Townhouse New England Victoria)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197097, 'New Market House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197177, 'Pasha Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197182, 'Portobello House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197184, 'Primrose Guest House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197215, 'Измайлово Дельта', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197326, 'Regency House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197767, 'The Black Lion', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (197769, 'The Bridge Hotel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (205282, 'London Heathrow Marriott Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (205492, 'New Cross Inn', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (205524, 'Presidential Marylebone', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (211308, 'Ibis London Heathrow Airport', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (211435, 'W12 Rooms', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (212333, 'Рослеспром', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (248772, '274 Suites', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (265133, 'Apple House Guest House Heathrow Airport', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (270946, 'So Paddington Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (277866, 'Royal London Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (278055, 'Searcys Roof Garden Rooms', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (278117, 'Simply Rooms & Suites', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (278270, 'Sydney House Chelsea', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (279137, 'The Craven Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (279299, 'The Garth Hotel - B&B', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (279406, 'The Harrison', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (279425, 'The Grand at Trafalgar Square', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (295942, 'The Lanesborough - Oetker Collection Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (296622, 'Sloane Square Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (297279, 'The Windermere Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (297404, 'Tony S House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (297520, 'Tune Hotel  Westminster', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (297871, 'Windmill Guest House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (297874, 'Windsor House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (297877, 'Oyo London 24 Sussex. ( ex. Winrose Hotel )', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (298009, 'Islington Inn (ex. Tommy Miahs Raj Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (300763, 'Берлин', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (305990, 'СПБВЕРГАЗ', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (307776, 'Citadines Trafalgar Square London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (324157, 'Qbic Hotel London City', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (332553, 'МКМ (ранее Москабельмет)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (333874, '54 (Fifty Four) Boutique Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (334290, 'Paddington Park Hotel (ex.Oxford Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (334302, 'Queens Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (334526, 'ST ATHANS HOTEL', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (335327, 'Abbey Point Cafe B&b', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (335368, 'Apollo Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (341184, 'Sunborn London Yacht Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (341522, 'Chelsea Guest House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (341533, 'Cheval Gloucester Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (341534, 'Cheval Knightsbridge', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (341537, 'Cheval Thorney Court', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (341540, 'Cheval Three Quays', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (341733, 'Collingham Serviced Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (342185, 'Cheval Harrington Court at South Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (342192, 'Haverstock Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (342662, 'London City Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (342663, 'London City Suites by Montcalm (The Barbican Rooms)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (342665, 'London Guest House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (342702, 'Marlin Aldgate - Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (342769, 'No.5 Maddox Street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (342813, 'Olympia Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (343048, 'Roseview Alexandra Palace Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (343090, 'Sapphire Hotel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (343877, 'The Harrington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (345261, 'Меркюр Москва Павелецкая', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (345424, 'Twenty Nevern Square Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (345484, 'Welcome Inn', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (346265, 'Адажио Москва Павелецкая (апарт-отель)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (353627, 'Ибис Москва Центр Бахрушина', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (355741, 'Hampton By Hilton London Waterloo', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (356208, '130 Queens Gate Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (358521, 'Парк Инн Аэропорт Пулково', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360667, '45 Park Lane - Dorchester Collection', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360672, 'Abbey Lodge Hotel - B&B', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360678, 'Alhambra Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360688, 'Belgrave Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360690, 'Belle Cour Hotel & Spa', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360700, 'Chester Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360701, 'City Lodge London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360703, 'City View Hotel - Roman Road Market', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360705, 'Classic Hyde Park Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360710, 'Eurotraveller Hotel-premier (tower Bridge)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360718, 'Georgian House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360724, 'Goodwood Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360732, 'Hotel 261', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360737, 'Hotel Unique', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360744, 'Kings Cross Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360751, 'Manor Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360757, 'Mayfair House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360760, 'Mentone Hotel - B&B', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360761, 'Mermaid Suite Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360793, 'Park Grand London Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360795, 'Piccolino Hyde Park Hotel (ex.Piccolino Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360796, 'The Portobello Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360834, 'St Georges Inn Victoria', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360836, 'Star Hotel - B&B', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360837, 'Studios2let - North Gower', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360838, 'Stylotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360842, 'The Clarendon Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360845, 'The Hide London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360853, 'Wardonia Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (360854, 'Westpoint Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (392195, 'Интурист Коломенское', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (395929, 'Гостиница Садовое кольцо', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (395941, 'Покровское-Стрешнево', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (396333, 'Валс отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (411086, 'Park Avenue Baker Street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (422623, 'Grenville Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (422649, 'Staycity Aparthotels London Greenwich High Road', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (429746, 'City Inn Express Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (442222, 'Меркюр Бауманская Москва', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (445389, 'Hilton London Tower Bridge', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (445696, 'Staybridge Suites London - Vauxhall', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (445810, 'Kensington Gardens (ex.TOP Kensington Gardens Hotel)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (457005, 'Marlin Apartments Canary Wharf', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (457008, 'Marlin Apartments Queen Street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (458373, 'DoubleTree by Hilton Moscow - Marina (ДаблТри Хилтон Москва-Марина)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (462149, 'Ascot Hyde Park Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (469352, 'Севастополь (Корпус Модерн)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (474978, 'Арена', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (498476, 'Point A Hotel - London, Canary Wharf', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507236, 'Bay Tree House Bed & Breakfast', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507259, 'Londons Home Limited - Central Hoxton Shoreditch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507305, 'Dawson Place, Juliettes Bed and Breakfast', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507331, 'Eden Plaza Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507341, 'Epsilon Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507390, 'George Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507412, 'Hammersmith One', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507466, 'Kensington and Chelsea Apartment', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507545, 'mk hotel london', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507548, 'Monument One', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507661, 'Saco London - Trinity Tower', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507663, 'Saint James Backpackers', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507669, 'Shepherds Bush Flats', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507734, 'The Apartments by The Sloane Club', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507736, 'The Clerk & Well Pub and Rooms', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507741, 'The Hoxton Holborn', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (507758, 'The Shoreditch Inn', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (514015, 'Holiday Inn Express London - Excel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (538616, '291 Suites', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (538654, 'Ibis Styles London Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (538703, 'Adria Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (538733, 'Albany Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (538956, 'Albion House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (539079, 'Apartments Inn London Pimlico', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (539080, 'Apartments Inn London Lancaster Gate', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (539195, 'Arosfa Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (539228, 'Aspen Serviced Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (539289, 'Balmoral House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (540019, 'Charlotte Guest House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (540032, 'Chelsea Bridge Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (540204, 'Clapham Guest House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (540875, 'Euro Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (541753, 'Heathrow Inn', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (542058, 'Hotel Oliver', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (542071, 'Hotel Strand Continental', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (542553, 'King William Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (542788, 'Lamington – Hammersmith Serviced Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (543049, 'London Court Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (543062, 'London Stay Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (547065, 'Принц Парк Отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (549892, 'Craven Gardens', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (573745, 'The Gateway Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (580751, 'Venture Hostel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (582622, 'The Royal Foundation of St Katharine', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (586164, 'Prince Regent Hotel Excel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (588531, 'SACO Holborn – Lamb’s Conduit St', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (590529, 'The Nadler Soho', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (590649, 'SO Arch Aparthotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (594424, 'The Shaftesbury Marble Arch Suites', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (597789, 'Dolphin House Serviced Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (600256, 'SoHostel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (631727, '9A Craven Road Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (632918, 'Grove Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (638087, 'Smart Russell Square Hostel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (639116, 'The Villa Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (639207, 'Glenlyn Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (639214, 'Avonmore Hotel Cartwright Gardens', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (639854, 'Rose Court Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (640895, 'Avoca House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (643778, 'Ибис Москва Динамо', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (666839, 'Astoria Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (690127, 'Хилтон Санкт-Петербург ЭкспоФорум', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (697177, 'Shepherds Bush Boutique Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (697256, 'The Laslett Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (701893, 'Intercontinental London - The O2', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (705944, 'Hilton London Bankside', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (709017, 'Маджестик Бутик Отель Делюкс', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (718063, 'Metro Star', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (721653, 'Никоновка', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (758273, 'Пальмира  Бизнес-клуб', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (764127, 'Первомайская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (772078, 'Серпуховской Двор', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (772844, 'The Captain Cook Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (772847, 'The One Tun Pub and Rooms', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (772863, 'SACO Covent Garden - Arne Street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (772864, 'SACO Covent Garden - St Martins', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (772866, 'Clayton Crown Hotel London (ex. Crown Moran)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (772868, 'Holborn One', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (772875, 'Anwar House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (773521, 'Хэмптон бай Хилтон Санкт-Петербург Экспофорум', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (778931, 'Ханой-Москва Апарт Отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (778953, 'Вертикаль Апарт-отель', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (785128, 'Ханзер Отель', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (798317, 'Новотель Москва Киевская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (798320, 'Ибис Москва  Киевская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (801732, 'Summerfield Pub & Boutique Rooms', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (801910, 'Novotel London Canary Wharf', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (802023, 'Montcalm Royal London House - City Of London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (802030, 'Leman Locke', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (802061, 'The Kings Head Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (802254, 'Four Seasons Hotel London At Ten Trinity Square', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (802587, 'Fitzrovia Belle Public House & Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (802599, 'citizenM London Shoreditch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (802652, 'Imperial Court Suites', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (803519, 'Wimbledon Holiday Lets', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (803895, 'Good Hotel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (804395, 'Mercure London Heathrow (ex. Comfort Hotel Heathrow)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (804593, 'Room 2 by Lamington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (804615, 'Euston Square Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (804616, 'London Euston Luxury Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (805860, 'Monopoly Accommodations', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (805922, 'ibis Styles London Ealing (Opening soon)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (806312, 'Park Plaza London Waterloo', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (806313, 'Park Plaza London Park Royal', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (806367, 'The Forester Ealing', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (806478, 'SACO The Cannon', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (806502, 'Kip Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (806509, 'Courthouse Hotel Shoreditch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (806555, 'citizenM Tower of London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (806558, 'The Bryson Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (806559, 'Morgan Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (807510, 'Lion & Key Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (810621, 'Адажио Москва Киевская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (811943, 'Rez Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (812911, 'Phoenix Hostel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (813667, 'The Nadler Victoria', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (813687, 'The Bull and The Hide', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (813884, 'MStay39 Studios', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (814470, 'The Westbourne Hyde Park', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (814486, 'The Tower Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (819848, 'Belmont Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (838800, 'Imperial Court Studios', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (843710, 'Heeton Concept Hotel-Luma Hammersmith (ex. Luma Concept Hotel London)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (851021, 'МФК Горный', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (861913, 'Хилтон Гарден Инн Москва Красносельская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (872120, 'Hampton By Hilton London Docklands', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (873029, 'SACO Fitzrovia', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (874385, 'Point A hotel London Shoreditch', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (877340, 'Absolute Pleasure Yacht', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (877860, 'Lansbury Heritage Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (885502, 'Kensington and Chelsea grand apartment', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (888527, 'Garden Embassy (Гарден Эмбасси)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (909986, 'Ибис Москва Октябрьское Поле', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (909988, 'Ибис Баджет Москва Панфиловская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (910099, 'Лотте Отель Санкт-Петербург', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (912072, 'Отель Парк Английская Набережная (б. История на Английской Набережной)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (914838, 'House of Toby', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (914860, 'MSTAY GOLDERS GREEN', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (914868, 'Marlin Waterloo', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (927040, 'Ibis London Canning Town', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (954684, 'Comfotel Prpl', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (954710, 'Lambeth North One', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (954755, 'Hyatt Place West London/Hayes (ex. Hyatt Place London Heathrow/Hayes)', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (955704, 'Cricklewood Lodge Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (955971, 'Baker Street Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (976684, 'Причал', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (993593, 'Холидей Инн Экспресс Москва Павелецкая (Holiday Inn Express MOSCOW - PAVELETSKAYA)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (997581, 'Ибис Москва Аэропорт Домодедово', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (997666, 'easyHotel South Kensington', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (997669, 'Mimi’s Hotel Soho', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (997684, 'Mstay Paddington Rooms', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1005281, 'Холидей Инн Экспресс Санкт-Петербург Садовая (Holiday Inn Express ST. PETERSBURG  - SADOVAYA)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1017221, 'City Stay Serviced Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1017365, 'Арт Москва Войковская', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1017574, 'The Grange Pub', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1020642, 'The Henrietta Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1022272, 'Brooklyn House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1026179, 'Wilde Aparthotels by Staycity The Strand', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1030171, 'The Green W7', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1030331, 'Hellenic Hotel London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1030561, 'The Albion', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1032149, 'Forest House Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1035270, 'Paddington Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1038949, 'Central London Flat Westminster', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1040967, 'The Duke Rooms London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1042283, 'Rouge Estate Ealing', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1045339, 'New Road Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1048096, 'The Westerly London', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1049433, 'Rainbow Studios Canary Wharf', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1050223, 'Edgware Road Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1050231, 'Paddington Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1052478, 'The Beverley Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1052598, 'Melandre Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1053724, 'Forest in City Lodge', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1059000, 'SMJ Groups', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1064141, '56 Welbeck Street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1064775, 'Amity Hostel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1067467, 'Kensington Prime Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1067643, 'City Aldgate Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1068869, 'Barber Studio', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1075470, 'Hyde Park Radnor Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1075880, 'The Grafton Arms', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1076815, 'Avo Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1078451, 'Kimberley Gardens House', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1078806, 'Maddox Street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1082209, 'Beautiful Rooms Near Excel Center', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1082632, '35 Hyde Park Gate', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1082806, 'Aldgate Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1082824, 'Excel Apartments Bloomsbury 2', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1082837, 'easyHotel Old Street Barbican', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1083043, 'Thirty Sussex Hotel', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1088790, 'The Hurdwick', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1092372, 'Heatherbank Guesthouse', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1093576, 'flex apartment', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1094558, 'Q Soho', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1094740, 'Kempsford House Apartments', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1100071, 'City view flat at Liverpool st Brick Ln', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1100081, 'Excel Apartments St.Pauls', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1101162, 'The Pear Tree', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1101577, 'London Heathrow Airport Rooms B.R by C&P', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1103107, 'Private en-suite Room Liverpool street', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1105268, 'Guest House Ellipse', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1105344, 'Холидей Инн Экспресс Москва - Ховрино (Holiday Inn Express MOSCOW - KHOVRINO)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1105919, 'Simple Studio flat in heart of Brick ln', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1105956, 'Roomzzz London Stratford', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1115800, 'Гостиница Театральная площадь (быв. Майнингер Санкт-Петербург Никольские ряды)', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1128361, 'Custos Hotel Riverside (Кустос Риверсайд)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1128362, 'Custos Hotel Tsvetnoy (Кустос Цветной)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1172726, 'Diamond Apartments', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1176632, 'Pentahotel Moscow Arbat', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1185222, 'Волков', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1200409, 'Усадьба на Елизарова', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1203889, 'Рэдиссон Блу Олимпийский', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1218948, 'Аэротель Экспресс', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1224778, 'Custos Hotel Tverskaya (Кустос Тверская)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1224991, 'Holiday Inn Express MOSCOW - BAUMANSKAYA', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1225590, 'Great Cumberland Place', 1)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1230449, 'Custos Hotel Lubyansky (Кустос Лубянский)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1253572, 'Интермарк Резиденс', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1259109, 'Царицынский комплекс', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1273278, 'Нептун', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1273699, 'Крылатское', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1273701, 'Отель Инсайд Транзит', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1275525, 'Отель Таврический', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1277675, 'Вертикаль Мы и Я', 3)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1282613, 'Мовенпик Москва Таганская (Movenpick Moscow Taganskaya)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1284050, 'Марина хостел', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1284338, 'Parradosso', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1285353, 'Вертикаль Бутик БВ Сигначе Коллекшен (Vertical Boutique BW Signature Collection)', 2)");
        $this->addSql("INSERT INTO hotel (id, name,city_id) VALUES (1288012, 'Орбиталь', 3)");
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE hotel');
        $this->addSql('DROP TABLE meal');
        $this->addSql('DROP TABLE search_request');
        $this->addSql('DROP TABLE search_result');
        $this->addSql('DROP TABLE special_offer');
    }
}
